# Generated by Django 5.2.1 on 2026-03-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image', models.ImageField(upload_to='affiliate_partners/')),
                ('description', models.CharField(max_length=220)),
                ('perks', models.TextField(help_text='One perk per line')),
                ('cta_label', models.CharField(default='View Partner', max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliate Partner',
                'verbose_name_plural': 'Affiliate Partners',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
