# Generated by Django 5.2.1 on 2026-03-18 15:57

import django.db.models.deletion
import vv_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='perks',
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='full_logo',
            field=models.ImageField(blank=True, help_text='Optional but recommended. Wider version for premium presentation.', null=True, upload_to=vv_app.models.partner_full_logo_upload_to),
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='logo',
            field=models.ImageField(default=1, help_text='Required. Main partner image/logo for the homepage and brand display.', upload_to=vv_app.models.partner_logo_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='long_description',
            field=models.TextField(blank=True, help_text='Optional full description for the individual partner page.'),
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='main_description',
            field=models.TextField(default=1, help_text='Primary partner description.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='short_description',
            field=models.CharField(blank=True, help_text='Optional short text used for compact displays.', max_length=220),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Optional external URL. If left blank, the internal partner detail page will be used.', max_length=255),
        ),
        migrations.CreateModel(
            name='AffiliatePartnerGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vv_app.models.partner_gallery_upload_to)),
                ('description', models.CharField(blank=True, help_text='Optional description shown below the gallery image.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vv_app.affiliatepartner')),
            ],
            options={
                'verbose_name': 'Affiliate Partner Gallery Image',
                'verbose_name_plural': 'Affiliate Partner Gallery Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
