# Generated by Django 5.2.1 on 2026-03-18 16:57

import vv_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv_app', '0002_remove_affiliatepartner_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatepartnergalleryimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='cta_url',
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='landing_page_url',
            field=models.URLField(blank=True, help_text='Optional landing page URL shown on the partner detail page.'),
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='website_url',
            field=models.URLField(default=1, help_text='Required external website URL for the homepage CTA.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='full_logo',
            field=models.ImageField(blank=True, help_text='Optional but recommended. Wider version.', null=True, upload_to=vv_app.models.partner_full_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='logo',
            field=models.ImageField(help_text='Required. Main partner image/logo.', upload_to=vv_app.models.partner_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='main_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='short_description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='affiliatepartnergalleryimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
