# Generated by Django 5.2.1 on 2026-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv_app', '0003_alter_affiliatepartnergalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepartner',
            name='cta_label',
            field=models.CharField(default='Visit Partner', max_length=40),
        ),
    ]
